[package]
name = "logos-derive"
version = "0.9.2"
authors = ["maciejhirsz <maciej.hirsz@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Create ridiculously fast Lexers"
repository = "https://github.com/maciejhirsz/logos"
documentation = "https://docs.rs/logos-derive"
keywords = ["lexer", "lexical", "tokenizer", "parser", "no_std"]
categories = ["parsing", "text-processing"]
readme = "../README.md"
edition = "2018"

[lib]
name = "logos_derive"
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["extra-traits", "full"] }
quote = "0.6"
proc-macro2 = "0.4"
regex-syntax = "0.6"
utf8-ranges = "1.0"
