[package]
name = "logos-derive"
version = "0.12.1"
authors = ["Maciej Hirsz <hello@maciej.codes>"]
license = "MIT OR Apache-2.0"
description = "Create ridiculously fast Lexers"
repository = "https://github.com/maciejhirsz/logos"
documentation = "https://docs.rs/logos-derive"
keywords = ["lexer", "lexical", "tokenizer", "parser", "no_std"]
categories = ["parsing", "text-processing"]
readme = "../README.md"
edition = "2018"

[lib]
name = "logos_derive"
proc-macro = true

[dependencies]
logos-codegen = { version = "0.12.0", path = "../logos-codegen" }
