[package]
name = "logos-derive"
version = "0.6.0"
authors = ["maciejhirsz <maciej.hirsz@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Create ridiculously fast Lexers"
repository = "https://github.com/maciejhirsz/logos"
documentation = "https://docs.rs/logos-derive"
readme = "../README.md"

[lib]
name = "logos_derive"
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["extra-traits", "full"] }
quote = "0.6"
proc-macro2 = "0.4.4"
regex-syntax = "0.6"
