[package]
name = "logos"
version = "0.2.0"
authors = ["maciejhirsz <maciej.hirsz@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Create ridiculously fast Lexers"
repository = "https://github.com/maciejhirsz/logos"
documentation = "https://docs.rs/logos"
readme = "../README.md"

[dependencies]
toolshed = { version = "0.6", optional = true }

[dev-deppendencies]
logos-derive = { path = "../logos-derive" }

[features]
default = []
nul_term_source = ["toolshed"]
