[book]
authors = ["Maciej Hirsz <hello@maciej.codes>", "JÃ©rome Eertmans (maintainer) <jeertmans@icloud.com>",]
language = "en"
src = "src"
title = "Logos Handbook"

[output.html]

[output.linkcheck2]
